apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: l1v1en87g-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap-test-organization-jk/rhtap-qe:0c17e1d8da3619839f8ca689a3cf25eff19e6522@sha256:4a1a6a33686d416327fb1524eb81ffc93bfdd65cd3175ed9b138c834e368c58b
        name: container-image  
